### ISSUE TITLE
[zimbra_populateserver.sh] but in dl population

### ISSUE THREAD

**Issue by barrydegraaff** [mrCine/ZimbraScripts#1]
Creating 10 Distribution Lists
Populating Distribution Lists
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)

Seems there still is a variable not updating...

**Comment by mrCine** [comment]
Hello!

Can you please tell me the arguments you used when running the script?

**Comment by barrydegraaff** [comment]
./zimbra_populateserver.sh -d 1
./zimbra_populateserver.sh: line 55: [: -ne: unary operator expected

**Comment by mrCine** [comment]
Should be fixed in commit 239fc099d80e104054a413ac1b4fe30dab1970a9, do you confirm?

**Comment by barrydegraaff** [comment]
error is gone, but still does not work

Populating Distribution Lists
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)
ERROR: account.NO_SUCH_DISTRIBUTION_LIST (no such distribution list: dl0@example0.com)

**Comment by mrCine** [comment]
Verified fixed
